config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :teams, :path => '', param: :slug, only: [:show]
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  protected

  def to_slug(string)
    string.parameterize
  end
end

app/models/team.rb
class Team < ApplicationRecord
  default_scope { order('name') }

  def to_param
    slug
  end

  def games_played
    team_stats[:gamesPlayed]
  end

  def wins
    team_stats[:wins]
  end

  def losses
    team_stats[:losses]
  end

  def ot_losses
    team_stats[:ot]
  end

  def points
    team_stats[:pts]
  end

  def division_rank
    team_standings[:divisionRank]
  end

  def conference_rank
    team_standings[:conferenceRank]
  end

  def league_rank
    team_standings[:leagueRank]
  end

  def team_roster
    Rails.cache.fetch('team_roster', expires_in: 5.minutes) do
      NHLAPI::Team.new(id).get_roster
    end
  end

  private

  def team_stats
    Rails.cache.fetch('team_stats', expires_in: 5.minutes) do
      NHLAPI::Team.new(id).get_stats
    end
  end

  def team_standings
    Rails.cache.fetch('team_standings', expires_in: 5.minutes) do
      NHLAPI::Team.new(id).get_standings
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def show
    status_code = params[:code] || 500
    render status_code.to_s, status: status_code
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def index
    @teams = Team.all
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def show
    raise ActionController::RoutingError.new('Not Found') if current_team.blank?
  end

  private

  helper_method :current_team
  def current_team
    @current_team ||= Team.find_by(slug: params[:slug])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
  def player_name(player)
    player[:person][:fullName]
  end

  def number(player)
    player[:jerseyNumber]
  end

  def position(player)
    player[:position][:abbreviation]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hockeyhub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag params[:controller] if Rails.application.assets_manifest.assets["#{params[:controller]}.css"] %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<div class="bg">
  <div class="banner">
    <h2>Hockey Hub </h2>
  </div>

  <div class="index-wrapper">
    <div class="index-box">
      <div class="dropdown show">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Pick a team
        </a>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <% @teams.each do |team| %>
            <%= link_to team.name, team_path(team), class:"dropdown-item" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>